services:
  db:
    image: mysql:8
    container_name: restaurant_edible_db
    networks:
      - restaurant
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_USER: restaurant_edible
      MYSQL_PASSWORD: restaurant_edible
      MYSQL_DATABASE: edible
    ports:
      - 4002:3306
    expose:
      - 4002
    volumes:
      - edible:/var/lib/mysql
    restart: on-failure

  app:
    build:
      context: ../../
      dockerfile: config/Dockerfile
    container_name: restaurant_edible_app
    environment:
      APP_MODE: $APP_MODE
    ports:
      - 9002:80
    expose:
      - 9002
    networks:
      - restaurant
    depends_on:
      - db
    restart: on-failure
    command: "/app/server"

networks:
  restaurant:
    name: restaurant

volumes:
  edible:
    name: restaurant_edible
